catalog:
  '@types/node': 'npm:@types/node@24.12.2'
  vite: 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1633'
  vite-plus: 'https://pkg.pr.new/voidzero-dev/vite-plus@1633'
  vitest: 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-test@1633'

nodeLinker: node-modules

npmScopes:
  jsr:
    npmRegistryServer: 'https://npm.jsr.io'

yarnPath: .yarn/releases/yarn-4.13.0.cjs
