approvedGitRepositories:
  - "**"

catalog:
  "@types/node": "npm:@types/node@24.12.2"
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.0fecc75a64a39bc5600ff6a1cee8baff378a8cc1
  vite-plus: 0.0.0-commit.0fecc75a64a39bc5600ff6a1cee8baff378a8cc1
  vitest: 4.1.9

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  jsr:
    npmRegistryServer: "https://npm.jsr.io"

yarnPath: .yarn/releases/yarn-4.17.0.cjs
npmPreapprovedPackages:
  - vitest
  - '@vitest/*'
npmRegistryServer: https://registry-bridge.viteplus.dev/
