catalog:
  '@types/node': 'npm:@types/node@24.12.2'
  vite: 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1738'
  vite-plus: 'https://pkg.pr.new/voidzero-dev/vite-plus@1738'
  vitest: 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-test@1738'

nodeLinker: node-modules

npmMinimalAgeGate: 60m
npmPreapprovedPackages:
  - vite-plus
  - vite
  - vitest
  - '@voidzero-dev/*'
  - '@oxc-project/*'
  - '@oxlint/*'
  - oxlint
  - oxfmt
  - oxlint-tsgolint

npmScopes:
  jsr:
    npmRegistryServer: 'https://npm.jsr.io'

yarnPath: .yarn/releases/yarn-4.13.0.cjs
